import React, { useState, useEffect, useRef } from 'react';
import { SettingsPanel } from './components/SettingsPanel';
import { GameButton } from './components/GameButton';
import { HistoryList } from './components/HistoryList';
import { audioService } from './services/audioService';

const ROLL_DURATION_MS = 4000;
const ANIMATION_INTERVAL_MS = 80;

const App: React.FC = () => {
  // Configuration State
  const [maxNumber, setMaxNumber] = useState<number>(100);

  // Game State
  const [history, setHistory] = useState<number[]>([]);
  const [availableNumbers, setAvailableNumbers] = useState<number[]>([]);
  const [currentDisplay, setCurrentDisplay] = useState<number | string | null>(null);
  const [isRolling, setIsRolling] = useState<boolean>(false);
  const [isFinished, setIsFinished] = useState<boolean>(false);

  // Refs for animation loop
  const intervalRef = useRef<number | null>(null);
  const timeoutRef = useRef<number | null>(null);

  // Initialize number pool when maxNumber changes
  useEffect(() => {
    resetGame(maxNumber);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); // Only on mount

  const resetGame = (newMax: number) => {
    const numbers = Array.from({ length: newMax }, (_, i) => i + 1);
    setAvailableNumbers(numbers);
    setHistory([]);
    setCurrentDisplay(null);
    setIsFinished(false);
    setIsRolling(false);

    // Clear any active timers
    if (intervalRef.current) clearInterval(intervalRef.current);
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
  };

  const handleUpdateMax = (n: number) => {
    setMaxNumber(n);
    resetGame(n);
  };

  const startRoll = () => {
    if (availableNumbers.length === 0) {
      setIsFinished(true);
      return;
    }

    setIsRolling(true);
    audioService.playRinging(ROLL_DURATION_MS / 1000);

    // 1. Rapidly change numbers for visual effect
    intervalRef.current = window.setInterval(() => {
      // Show random number from 1 to MaxNumber (doesn't have to be from available pool for the visual effect)
      // This makes it look more "random" while spinning
      const randomVisual = Math.floor(Math.random() * maxNumber) + 1;
      setCurrentDisplay(randomVisual);
    }, ANIMATION_INTERVAL_MS);

    // 2. Stop after duration and pick real winner
    timeoutRef.current = window.setTimeout(() => {
      stopRoll();
    }, ROLL_DURATION_MS);
  };

  const stopRoll = () => {
    if (intervalRef.current) {
      clearInterval(intervalRef.current);
      intervalRef.current = null;
    }

    // Pick a winner from the available pool
    const randomIndex = Math.floor(Math.random() * availableNumbers.length);
    const winner = availableNumbers[randomIndex];

    // Update State
    setCurrentDisplay(winner);
    setHistory(prev => [...prev, winner]);

    // Remove winner from pool
    const newPool = [...availableNumbers];
    newPool.splice(randomIndex, 1);
    setAvailableNumbers(newPool);

    setIsRolling(false);
    audioService.playSuccess();

    if (newPool.length === 0) {
      setIsFinished(true);
    }
  };

  return (
    <div className="min-h-screen flex flex-col items-center py-8 bg-black text-slate-50">
      <header className="mb-6 text-center">
        <h1 className="text-4xl font-extrabold text-white tracking-tight mb-2">
          幸運抽獎
        </h1>
        <p className="text-slate-400">
          點擊按鈕抽取不重複號碼 (1 - {maxNumber})
        </p>
      </header>

      <SettingsPanel
        maxNumber={maxNumber}
        onUpdateMaxNumber={handleUpdateMax}
        onReset={() => resetGame(maxNumber)}
        disabled={isRolling}
      />

      <main className="flex-1 flex flex-col items-center justify-center w-full">
        <GameButton
          displayNumber={currentDisplay}
          isRolling={isRolling}
          isFinished={isFinished}
          onClick={startRoll}
        />

        {isFinished && !isRolling && (
          <div className="mt-8 px-6 py-3 bg-indigo-900/50 text-indigo-100 border border-indigo-700 rounded-full font-bold animate-bounce">
            號碼已全數抽完！
          </div>
        )}
      </main>

      <HistoryList history={history} />

      <footer className="mt-12 text-center text-slate-400 text-sm">
        Generated by AI • React • Tailwind
      </footer>
    </div>
  );
};

export default App;